### ISSUE TITLE
is_valid always return true

### ISSUE THREAD

**Issue by devfaysal** [overint/php-mailgun-validation#3]
```
public function validate($email)
    {
        $ret = $this->queryMailgun($email);
        return $ret->is_valid;
    }
```
This function is returing always true.
After looking at the full response, I found that if we return `mailbox_verification`, it is distinguishing well.
`mailbox_verification == true` when email is valid and when email is invalid, `mailbox_verification == "unknown"`

**Comment by overint** [comment]
As per the docs, it seems it's correct to return the `is_valid` param?
https://documentation.mailgun.com/en/latest/api-email-validation.html#example

**Comment by devfaysal** [comment]
Please check the Note below the documentation:
The real verification result will come from mailbox verification.

> Note is_valid returns true when an address is parsable, passes known grammar checks and an SMTP server is present. The role-based and disposable address check will not impact the state of the is_valid result. The user should determine whether or not to permit the address to be used.

> Note The mailbox verification attribute will return true if the email is valid, false if the email was invalid, or unknown if the SMTP request could not be completed. Unknown will also be returned if mailbox verification is not supported on the target mailbox provider. The outcome of the verification check will not impact the state of the is_valid result.

**Comment by overint** [comment]
Perhaps the return of `validate` should be 
```php
$ret->is_valid === true && $ret->mailbox_verification !== false
```

**Comment by devfaysal** [comment]
This looks good. But they are saying it will return unknown if the SMTP request could not be completed and Unknown will also be returned if mailbox verification is not supported on the target mailbox provider
I am also thinking about these 2. Lets take some time to get a good solution. I will be working on it, and will let you know if I get any good solution.

**Comment by overint** [comment]
No worries, feel free to open a PR.

**Comment by devfaysal** [comment]
As you propossed `$ret->is_valid === true && $ret->mailbox_verification !== false` , it will work fine if we turn on mailbox_verification.
I had some confusion because all response was either true or unknown. I was not getting the false response. But after several conversations with mailgun, I fund that we need to turn on the mailbox verification to get a false response.
So we need to `add &mailbox_verification=true` in the url.

**Comment by overint** [comment]
Closed by https://github.com/overint/php-mailgun-validation/pull/4
